baseURL = 'https://angelcastrejon.com/'
languageCode = 'en-us'
title = 'Angel Castrejon'
theme = 'pico-theme'

[params]
environment = 'default'
author = 'Angel Castrejon'
subtitle = 'Data Engineer | Analytics Engineer | AI & ML Enthusiast'
bio = 'I am a Data and Analytics Engineer by trade, who has also architected data solutions at an enterprise scale. My journey began at GameFly as a Business Analyst Intern, where I was later hired full-time after completing my Bachelors degree in Computer Science from CSU Fullerton.'
summaryLength = 33

    [params.social]
        linkedin = 'oangelcastrejon'
        github = 'angelcastrejon'

[security]
    enableInlineShortcodes = false

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

